#!C:\cygwin64\bin\bash
node {
	try {

		stage("Validate") {
			// check the input parameters
			assert env.GITHUB_PROJECT?.trim() : "The environment variable GITHUB_PROJECT is required!"
			assert env.BUILD_BRANCH?.trim()      : "The environment variable Build branch is required!"
			
        	}
	
		stage ("checkout"){
			def message = "\u272A Using the following parameters:\n" +
                      "\u272A   GITHUB_PROJECT       : ${GITHUB_PROJECT}\n" +
                      "\u272A   BUILD_BRANCH            : ${BUILD_BRANCH}\n" 
		      
		      echo message
			git credentialsId: env.ADMIN_KEY, url: "git@github.com:${GITHUB_PROJECT}.git", branch: env.BUILD_BRANCH
		}
		
		stage ("Compile, package"){
			sh 'mvn clean package'
		
		}
		
		stage ("Archival"){
			step ([$class: 'ArtifactArchiver',
			artifacts: "target/*.?ar",
			excludes: null])
		
		}
	} catch (err){
		echo "Caught: ${err}"
	}

}
